[resource]
label = "Jina Web Reader"
name = "jina_web_reader"
version = "0.1.0"
description = "Convert any URL to an LLM-friendly input with a simple prefix https://r.jina.ai/"
authors = []
definition_type = "python"

[python_config]

[json_config]
